name: Build and Test (Web)

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/build_and_test.yml"
  pull_request:
    branches:
      - master
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/build_and_test.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.15.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Cache Turborepo build artifacts
      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Build web app
        run: yarn build --filter=@monthly/web

      - name: Run tests
        run: yarn test --filter=@monthly/web
